# Generated by Django 4.0.6 on 2022-08-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='generated_icons',
            field=models.ManyToManyField(blank=True, null=True, to='generator.favicons'),
        ),
    ]
